name: sesi_downloader
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  go_router: ^17.0.1
  google_fonts: ^7.0.2
  hooks_riverpod: ^3.1.0
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.0
  sizer: ^3.1.3
  window_manager: ^0.5.1
  riverpod_lint: ^3.1.0
  open_file: ^3.5.11
  skeletonizer: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/bin/
